services:
  ritmosbot:
    image: ritmosbot:v2.0
    container_name: ritmosbot
    depends_on:
      mongodb:
        condition: service_healthy
    # Reinicia cuando falla excepto cuando el apagado es manual
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - ritmosnet

  mongodb:
    image: mongorp:v2.0
    container_name: mongodb
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGODB_URI: ${MONGODB_URI}
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.mongo
    networks:
      - ritmosnet
    # Comprueba si MongoDB está listo ejecutando un ping con la URI completa.
    healthcheck:
      # Dentro del test, usamos $$MONGODB_URI (doble $) porque Docker interpreta YAML y debemos escapar el $
      test: >
        mongo "$$MONGODB_URI" --quiet --eval "db.runCommand({ ping: 1 }).ok" | grep 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

volumes:
  mongodb-data:

networks:
  ritmosnet:
    driver: bridge # Configuración de red personalizada para aislar los contenedores
