services:
  ritmosbot:
    image: ritmosbot:v2.0
    container_name: ritmosbot
    depends_on:
      - mongodb
      - lavalink
    # Reinicia cuando falla excepto cuando el apagado es manual
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - ritmosnet
    deploy:
      resources:
        limits:
          memory: 512M

  mongodb:
    image: mongorp:v2.0
    container_name: mongodb
    volumes:
      - mongodb-data:/data/db
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGODB_URI: ${MONGODB_URI}
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.mongo
    networks:
      - ritmosnet
    deploy:
      resources:
        limits:
          memory: 256M

  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:latest
    container_name: lavalink
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${LAVALINK_PORT}:${LAVALINK_PORT}"
    volumes:
      - ./lavalink/application.yml:/opt/Lavalink/application.yml
    networks:
      - ritmosnet
    deploy:
      resources:
        limits:
          memory: 384M

volumes:
  mongodb-data:

networks:
  ritmosnet:
    driver: bridge # Configuración de red personalizada para aislar los contenedores
