services:
  ritmosbot:
    image: ritmosbot:v2.0
    container_name: ritmosbot
    depends_on:
      - mongodb
    # Reinicia cuando falla excepto cuando el apagado es manual
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - ritmosnet

  mongodb:
    image: mongorp:v2.0
    container_name: mongodb
    volumes:
      - mongodb-data:/data/db
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGODB_URI: ${MONGODB_URI}
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.mongo
    networks:
      - ritmosnet

volumes:
  mongodb-data:

networks:
  ritmosnet:
    driver: bridge # Configuración de red personalizada para aislar los contenedores
