services:
  ritmosbot:
    image: ritmosbot:latest
    container_name: ritmosbot
    depends_on:
      - mongodb
    # Reinicia cuando falla excepto cuando el apagado es manual
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 2G

  mongodb:
    image: mongorp:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    # Reinicia cuando falla excepto cuando el apagado es manual
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.mongo

volumes:
  mongodb-data:
