server:
  port: ${LAVALINK_PORT}
  address: ${LAVALINK_ADDRESS}

lavalink:
  server:
    # Estabilidad del flujo UDP
    bufferDurationMs: 600
    frameBufferDurationMs: 5000

    # Seguridad
    password: ${LAVALINK_PASSWORD}

    # Fuentes de audio (deshabilitado por defecto youtube)
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: true
    
    # Filtros
    filters:
      volume: true
      equalizer: true
  plugins:
    # Uso de snapshot temporal
    - dependency: "dev.lavalink.youtube:youtube-plugin:2be8e542d3f6f178e048dca565892684c2e40177"
      snapshot: true

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - MUSIC
      - WEBEMBEDDED
      - ANDROID_VR
      - ANDROID_MUSIC
      - TV
      - IOS
      - WEB
      - MWEB

logging:
  file:
    path: ./logs/

  level:
    root: WARN
    lavalink: WARN
    dev.lavalink.youtube: WARN

  request:
    enabled: false

  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 5
