# Este workflow instala las dependencias, ejecuta los tests y el linter ESLint
# Para más información mira: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Ritmos CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
    - name: Clona el repositorio
      uses: actions/checkout@v4
    
    - name: Usando Node ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Instala las dependencias
      run: npm ci
    
    - name: Ejecuta los tests
      run: npm test

    - name: Ejecuta el linter ESLint
      run: npm run lint
