# Este workflow instala las dependencias, ejecuta los tests y el linter ESLint
# Para más información mira: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Ritmos CI

permissions:
  contents: read

on:
  push:
  pull_request:

# Si hay un action en progreso, cancela las actions antiguas si están en progreso
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x, 24.x]
    steps:
      - name: Clona el repositorio
        uses: actions/checkout@v4

      - name: Usando Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Instala las dependencias
        run: npm ci

      - name: Ejecuta los tests
        run: npm test

      - name: Ejecuta el linter ESLint
        run: npm run lint
