# Este workflow instala las dependencias, ejecuta los tests y el linter Biome
# Para más información mira: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Ritmos CI

permissions:
  contents: read

on:
  push:
  pull_request:

# Si hay un action en progreso, cancela las actions antiguas si están en progreso
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x, 24.x]
    steps:
      - name: Clona el repositorio
        # v7.0.1
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Configura Node.js ${{ matrix.node-version }}
        # v7.0.0
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version: ${{ matrix.node-version }}

      - name: Configura pnpm
        # v2.1.0
        uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b
        with:
          cache: true

      - name: Instala las dependencias
        run:  pnpm install --frozen-lockfile --ignore-scripts

      - name: Ejecuta los tests
        run: pnpm test

      - name: Ejecuta el linter Biome
        continue-on-error: true
        run: pnpm run lint
