# Este workflow instala las dependencias, ejecuta los tests y el linter ESLint
# Para más información mira: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Ritmos CI

permissions:
  contents: read

on:
  push:
  pull_request:

# Si hay un action en progreso, cancela las actions antiguas si están en progreso
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x, 24.x]
    steps:
      - name: Clona el repositorio
        # @v6.0.2
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Instala pnpm
        # @v5.0.0
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320
        with:
          version: 10

      - name: Usando Node ${{ matrix.node-version }}
        # @v6.3.0
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Instala las dependencias
        run:  pnpm install --no-frozen-lockfile --ignore-scripts

      - name: Ejecuta los tests
        run: pnpm test

      - name: Ejecuta el linter ESLint
        run: pnpm run lint
